"""initial

Revision ID: 155954cb3e65
Revises: 
Create Date: 2026-05-29 09:19:22.838146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '155954cb3e65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_item_id', sa.String(length=255), nullable=False),
    sa.Column('organizer_upn', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('queued', 'downloading', 'transcribing', 'extracting', 'awaiting_review', 'approved', 'sent', 'failed', name='processingstate'), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_drive_item_id'), 'meetings', ['drive_item_id'], unique=True)
    op.create_index(op.f('ix_meetings_state'), 'meetings', ['state'], unique=False)
    op.create_table('processed_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_item_id', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_items_drive_item_id'), 'processed_items', ['drive_item_id'], unique=True)
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('deadline_text', sa.String(length=255), nullable=True),
    sa.Column('deadline_iso', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidence'), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('edited_by', sa.String(length=255), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_upn', sa.String(length=255), nullable=False),
    sa.Column('is_organizer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_upn', name='uq_meeting_user')
    )
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_user_upn'), 'meeting_participants', ['user_upn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_participants_user_upn'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_processed_items_drive_item_id'), table_name='processed_items')
    op.drop_table('processed_items')
    op.drop_index(op.f('ix_meetings_state'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_drive_item_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
