"""add drive_id to processed_items

Revision ID: 5defbe6dc96a
Revises: 155954cb3e65
Create Date: 2026-05-29 10:04:41.781480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5defbe6dc96a'
down_revision: Union[str, None] = '155954cb3e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_items', sa.Column('drive_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_items', 'drive_id')
    # ### end Alembic commands ###
